---
name: Version bump ⬆

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  vbump:
    name: Bump version
    uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
